// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

string constant TOKEN_NAME_ENV_VAR = "TOKEN_NAME";
string constant TOKEN_SYMBOL_ENV_VAR = "TOKEN_SYMBOL";
string constant TOKEN_TOTAL_SUPPLY_ENV_VAR = "TOKEN_TOTAL_SUPPLY";
string constant ADMIN_ENV_VAR = "ADMIN";
string constant SUPPLY_REMAINDER_RECIPIENT_ENV_VAR = "SUPPLY_REMAINDER_RECIPIENT";
string constant UNISWAP_V2_ROUTER_ADDR_ENV_VAR = "UNISWAP_V2_ROUTER_ADDR";
string constant UNISWAP_V2_FACTORY_ADDR_ENV_VAR = "UNISWAP_V2_FACTORY_ADDR";
string constant UNISWAP_V3_POSITION_MANAGER_ADDR_ENV_VAR = "UNISWAP_V3_POSITION_MANAGER_ADDR";
string constant UNISWAP_V2_LIQUIDITY_LOCKER_ADDR_ENV_VAR = "UNISWAP_V2_LIQUIDITY_LOCKER";
string constant WETH_ADDR_ENV_VAR = "WETH_ADDR";
string constant RPC_URL_ENV_VAR = "RPC_URL";
string constant LOCK_DURATION_DAYS_ENV_VAR = "LOCK_DURATION_DAYS";
