// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

string constant ADMIN_ENV_VAR = "ADMIN";
string constant LIQUIDITY_TOKENS_RECIPIENT_ENV_VAR = "LIQUIDITY_RECIPIENT";
string constant PROTOCOL_TOKEN_ADDR_EVN_VAR = "PROTOCOL_TOKEN_ADDRESS";
string constant PAIR_TOKEN_ADDR_EVN_VAR = "PAIR_TOKEN_ADDRESS";
string constant WETH_ADDR_ENV_VAR = "WETH_ADDR";
string constant V3_POOL_FEE_ENV_VAR = "V3_POOL_FEE";
string constant LIQUIDITY_LOCKER_FEE_ENV_VAR = "LIQUIDITY_LOCKER_FLAT_FEE";
string constant DEADLINE_ENV_VAR = "DEADLINE";
string constant PROTOCOL_TOKEN_LIQUIDITY_ENV_VAR = "PROTOCOL_TOKEN_LIQUIDITY";
string constant PAIR_TOKEN_LIQUIDITY_ENV_VAR = "PAIR_TOKEN_LIQUIDITY";
string constant WETH_LIQUIDITY_ENV_VAR = "WETH_LIQUIDITY";
string constant CREATE_V2_POOLS_ENV_VAR = "CREATE_V2_POOLS";
string constant CREATE_V3_POOLS_ENV_VAR = "CREATE_V3_POOLS";
string constant LOCK_V2_LIQUIDITY_ENV_VAR = "LOCK_V2_LIQUIDITY";
string constant DEPLOYED_PROTOCOL_MANAGER_ADDR_ENV_VAR = "DEPLOYED_PROTOCOL_MANAGER_ADDR";
string constant DEPLOYED_V2_PROTOCOL_FACTORY_ADDR_ENV_VAR = "DEPLOYED_V2_PROTOCOL_FACTORY_ADDR";
string constant DEPLOYED_V3_PROTOCOL_FACTORY_ADDR_ENV_VAR = "DEPLOYED_V3_PROTOCOL_FACTORY_ADDR";
