# DLMP Protocol Dependencies
# Last updated: Mon Mar  3 11:12:17 EET 2025
# Format: owner/repo@version (one per line)
foundry-rs/forge-std@v1.9.6
OpenZeppelin/openzeppelin-contracts@v5.1.0
Uniswap/v2-core@v1.0.1
Uniswap/v2-periphery@v1.0.0-beta.0
Uniswap/v3-core@v1.0.0
Uniswap/v3-periphery@v1.3.0
